name: BetOrSpin Otomatik Guncelleme

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalışır
  workflow_dispatch:      # Manuel çalıştırma butonu

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Paketleri Yukle
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4 urllib3

      - name: BetOrSpin Calistir
        run: python betorspin.py

      - name: Değişiklikleri Commit ve Push Et
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add betorspin.m3u8
          git commit -m "Oto-Guncelleme: betorspin.m3u8" || echo "Degisiklik yok"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} main
