name: BOSS Sports M3U Generator

on:
  schedule:
    - cron: '0 12 * * *'  # Her gün saat 12:00 UTC
  workflow_dispatch:      # Manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run BOSS Sports M3U script
        run: |
          python boss.py

      - name: Upload generated M3U
        uses: actions/upload-artifact@v4
        with:
          name: boss-m3u
          path: boss.m3u
