name: Film Scraper

on:
  schedule:
    - cron: '0 2 * * *'   # Her gün 02:00 UTC
  workflow_dispatch:      # Manuel tetikleme

concurrency:
  group: film-json-update
  cancel-in-progress: true

jobs:
  update-films:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Önemli

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run film scraper
        run: |
          python film.py

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and push film.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin main
          git pull --rebase origin main
          git add film.json
          git commit -m "Film listesi güncellendi [GitHub Actions]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/mehmetey03/METV2.git main
