name: HDCH Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # 12 saatte bir çalışsın

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Playwright
        run: |
          pip install playwright beautifulsoup4 lxml
          playwright install --with-deps chromium

      - name: Run scraper
        run: python hdch.py

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: hdceh
          path: hdceh.json
