name: Jokerbet Auto Update

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Kontrol
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests cloudscraper urllib3

      - name: Scripti Calistir
        run: python joker.py

      - name: Kaydet ve Pushla
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [ -f joker.m3u8 ]; then
            git add joker.m3u8
            git diff --quiet && git diff --staged --quiet || (git commit -m "Update: $(date)" && git push)
          else
            echo "Dosya olusmadi!"
            exit 1
          fi
