name: MonoTV Guncelle

on:
  schedule:
    - cron: '0 */6 * * *' # 6 saatte bir
  workflow_dispatch:      # Elle başlatma butonu

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kütüphaneyi Kur
        run: pip install httpx

      - name: Scripti Çalıştır
        run: python mono.py

      - name: Değişiklikleri Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mono.m3u
          git commit -m "Liste güncellendi" || exit 0
          git push
