name: Update YouTube M3U
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # Her 3 saatte bir

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python 3.10 Yükle
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Kütüphaneleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: YouTube M3U Scriptini Çalıştır
        run: |
          cd METV2
          python youtube_m3u_generator.py

      - name: Değişiklik Kontrolü
        id: degisiklik_kontrol
        run: |
          cd METV2
          git diff --staged --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT

      - name: Değişiklikleri Commit Et ve Push
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          cd METV2
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add youtube.m3u
          git commit -m "YouTube M3U güncellendi - $(date +'%Y-%m-%d %H:%M') # FIX"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/mehmetey03/METV2.git HEAD:main
