name: Update YouTube M3U

on:
  schedule:
    - cron: '0 */3 * * *'  # Her 3 saatte bir
  workflow_dispatch:        # Manuel tetikleme

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token ile push için
    permissions:
      contents: write

    steps:
      - name: Repository'yi indir
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli kütüphaneleri yükle
        run: pip install requests

      - name: YouTube M3U scriptini çalıştır
        run: python youtube_m3u_generator.py

      - name: Değişiklik Kontrolü
        id: degisiklik_kontrol
        run: |
          git diff --quiet youtube.m3u || echo "degisiklik=true" >> $GITHUB_OUTPUT

      - name: Değişiklikleri Commit Et ve Push
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add youtube.m3u
          git commit -m "YouTube M3U güncellendi - $(date +'%Y-%m-%d %H:%M') # FIX" || echo "Commit yapılacak değişiklik yok"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/mehmetey03/METV2.git HEAD:main || echo "Push işlemi tamamlandı"
